
version: '3.5'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: SERVICE_NGINX_PROXY
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/unrestricted_body_size.conf:/etc/nginx/conf.d/unrestrict_body_size.conf
      - ./volumes/SERVICE_NGINX_PROXY_DATA/conf.d:/etc/nginx/conf.d
      - ./volumes/SERVICE_NGINX_PROXY_DATA/vhost.d:/etc/nginx/vhost.d
      - ./volumes/SERVICE_NGINX_PROXY_DATA/html:/usr/share/nginx/html
      - ./volumes/SERVICE_NGINX_PROXY_DATA/certs:/etc/nginx/certs:ro
      - ./volumes/SERVICE_NGINX_PROXY_DATA/htpasswd:/etc/nginx/htpasswd:ro
    networks:
      - service_network

  nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: SERVICE_NGINX_PROXY_LETSENCRYPT
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=${ENV_LETSENCRYPT_DEFAULT_EMAIL}
      - TZ=Europe/Berlin
    volumes:
      - ./volumes/SERVICE_NGINX_PROXY_DATA/conf.d:/etc/nginx/conf.d
      - ./volumes/SERVICE_NGINX_PROXY_DATA/vhost.d:/etc/nginx/vhost.d
      - ./volumes/SERVICE_NGINX_PROXY_DATA/html:/usr/share/nginx/html
      - ./volumes/SERVICE_NGINX_PROXY_DATA/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - service_network

networks:
  service_network:
    external: true
    driver: bridge
